# Generated by Django 2.2.3 on 2019-08-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0004_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200)),
                ('rulers', models.CharField(default='None', max_length=200)),
                ('religion', models.CharField(default='None', max_length=200)),
                ('location', models.CharField(default='None', max_length=200)),
                ('founder', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
