# Generated by Django 2.2.3 on 2019-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0005_auto_20190823_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
