# Generated by Django 2.2.3 on 2019-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0006_auto_20190823_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
