# Generated by Django 2.2.3 on 2019-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0008_auto_20190824_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='aliases',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='born',
            new_name='lovers',
        ),
        migrations.AddField(
            model_name='character',
            name='alive',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='religion',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='siblings',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='spouse',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
