# Generated by Django 2.2.3 on 2019-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0009_auto_20190825_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
