# Generated by Django 2.2.3 on 2019-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0010_auto_20190825_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='allegiances',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='culture',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='died',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='father',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='house',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='lovers',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='mother',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='playedBy',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='religion',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='siblings',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='character',
            name='spouse',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='titles',
            field=models.CharField(max_length=1000),
        ),
    ]
