# Generated by Django 2.2.3 on 2019-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0011_auto_20190825_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('culture', models.CharField(max_length=100)),
                ('born', models.CharField(max_length=100)),
                ('died', models.CharField(max_length=100)),
                ('titles', models.CharField(max_length=100)),
                ('aliases', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('allegiances', models.CharField(max_length=100)),
                ('playedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='book_1',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='book_2',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='book_3',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='book_4',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='book_5',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='s_1',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_2',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_3',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_4',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_5',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_6',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_7',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_8',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
        migrations.AddField(
            model_name='character',
            name='s_9',
            field=models.CharField(default='This section is empty,     you can help to improve our community by adding to it.', max_length=1000000),
        ),
    ]
