# Generated by Django 2.2.3 on 2019-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0012_auto_20190825_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='character',
            name='born',
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='character',
            name='alive',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='lovers',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='religion',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='siblings',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='spouse',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='allegiances',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='culture',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='died',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='father',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='mother',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='playedBy',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='titles',
            field=models.CharField(max_length=1000),
        ),
    ]
