# Generated by Django 2.2.3 on 2019-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0013_auto_20190825_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(default='', max_length=1000, upload_to=''),
        ),
    ]
