# Generated by Django 2.2.3 on 2019-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0016_userchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='', max_length=1000, upload_to=''),
        ),
    ]
