# Generated by Django 2.2.3 on 2019-09-12 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wikibsteros', '0017_city_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostACommentCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=2000)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikibsteros.Character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
