# Generated by Django 2.2.3 on 2019-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0019_postacommentarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='note',
            field=models.IntegerField(default=1),
        ),
    ]
