# Generated by Django 2.2.3 on 2019-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibsteros', '0020_character_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='note',
            field=models.FloatField(default=1.0),
        ),
    ]
